# -*- coding: utf-8 -*-
"""test_hotel_reservation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dm920295pY_33Ix4oAPksLCzJIILgLLj
"""

# Unit tests using unittest module
import unittest
import pickle


class TestHotel(unittest.TestCase):
    def setUp(self):
        self.hotel = Hotel('Test Hotel', 'Test Location', 10)

    def test_save_load_delete_hotel(self):
        self.hotel.save_to_file()
        loaded_hotel = pickle.load(open('Test Hotel', 'rb'))
        self.assertEqual(loaded_hotel.name, self.hotel.name)
        self.assertEqual(loaded_hotel.location, self.hotel.location)
        self.assertEqual(loaded_hotel.rooms, self.hotel.rooms)
        self.hotel.delete_file()
        with self.assertRaises(FileNotFoundError):
            pickle.load(open('Test Hotel', 'rb'))


class TestCustomer(unittest.TestCase):
    def setUp(self):
        self.customer = Customer('Test Customer', 'test@example.com')

    def test_save_load_delete_customer(self):
        self.customer.save_to_file()
        loaded_customer = pickle.load(open('Test Customer', 'rb'))
        self.assertEqual(loaded_customer.name, self.customer.name)
        self.assertEqual(loaded_customer.email, self.customer.email)
        self.customer.delete_file()
        with self.assertRaises(FileNotFoundError):
            pickle.load(open('Test Customer', 'rb'))


class TestReservation(unittest.TestCase):
    def setUp(self):
        self.customer = Customer('Test Customer', 'test@example.com')
        self.hotel = Hotel('Test Hotel', 'Test Location', 10)
        self.reservation = Reservation(self.customer, self.hotel)

    def test_save_load_delete_reservation(self):
        self.reservation.save_to_file()
        loaded_reservation = pickle.load(open('Test Customer_Test Hotel', 'rb'))
        self.assertEqual(loaded_reservation.customer.name, self.customer.name)
        self.assertEqual(loaded_reservation.hotel.name, self.hotel.name)
        self.reservation.delete_file()
        with self.assertRaises(FileNotFoundError):
            pickle